### PR TITLE
Align outbound content-type to the payload type

### LINKED ISSUE #3: Switch from `@Transformer` to @ServiceActivator`
For example the following pipeline that uses `file` source to read file’s content (octet type) applies `transform` to extract the file names form the header, which practically alters the content type to text:
```
file --filename-pattern='*.log' --directory=/tmp --prevent-duplicates=false | transform --expression=headers[file_name] | log
```
This fails in the transform module:
```
Caused by: java.lang.IllegalStateException: Failed to convert message: 'GenericMessage [payload=com.wacom.TabletHelper.so.log, headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=filetest.file, amqp_deliveryTag=2, file_name=com.wacom.TabletHelper.so.log, deliveryAttempt=3, amqp_consumerQueue=filetest.file.filetest, amqp_redelivered=false, file_originalFile=/tmp/com.wacom.TabletHelper.so.log, file_relativePath=com.wacom.TabletHelper.so.log, amqp_receivedRoutingKey=filetest.file, id=789348da-4bde-d242-a772-6bec0184b939, amqp_consumerTag=amq.ctag-acFRbva_SKTQqJsSv_Eywg, contentType=application/octet-stream, timestamp=1526295823965}]' to outbound message.
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$OutboundContentTypeConvertingInterceptor.doPreSend(MessageConverterConfigurer.java:324) ~[spring-cloud-stream-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.cloud.stream.binding.MessageConverterConfigurer$AbstractContentTypeInterceptor.preSend(MessageConverterConfigurer.java:351) ~[spring-cloud-stream-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.integration.channel.AbstractMessageChannel$ChannelInterceptorList.preSend(AbstractMessageChannel.java:589) ~[spring-integration-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:435) ~[spring-integration-core-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
```
( the `com.wacom.TabletHelper.so.log` is the file name) 
Exception comes from https://goo.gl/mgaXtd  and is likely related to the fact that the message payload has changed to `text` but the `content-type` in the header is still `octet`.  Later combination doesn’t match with any of the pre-configured message converters.
The solution used for the Log app will not help here! Instead to solve this we have to change the output content type (either explicitly with new property or find some smart way to determine the right output type).

### PR DESCRIPTION
**Pull request by tzolov**
If the outbound payload type is different from the inbound such then
the outbound content-type header should be aligned with the new payload type.
    
Discrepancy between the outbound payload type and the content-type metadata
may cause selecting incorrect message converter and therefore fail to encode
the outbound message into an appropriate wire format.
    
Due to https://jira.spring.io/browse/INT-4397 the @Transfomer annotated processors
blindly copy their input message headers into the output headers with no
regards of the outbound payload type.
    
The implementation of the @ServiceActivator doesn't suffer from this problem and can
be used as drop-in workaround.
    
Resolves #3

### CODE REVIEW

**Comment by artembilan** [comment]
Looks like related to this one: https://jira.spring.io/browse/INT-4397

**Comment by tzolov** [comment]
@artembilan, yes i believe it is caused by INT-4397

**Review by artembilan — CHANGES_REQUESTED** [review]
OK. I can review and merge this PR after the "Why?" explanation in the commit message: https://chris.beams.io/posts/git-commit/

Would be great to let everybody to know what's going on and don't play spy games here.

Thanks for understanding.

**Comment by tzolov** [comment]
@artembilan i've added some context to the commit message.

**Comment by artembilan** [comment]
Cool, @tzolov !

One remark though: when we use annotations in the commit message (symbol `@`), we should wrap that into the code (backticks) otherwise we may call a user here on GitHub, when such a commit message becomes a PR description :smile:.

**Pull request merged**
